### ISSUE TITLE
undefined method "each_file" for nil:NilClass when deploying v0.3.0 to Heroku

### ISSUE THREAD

**Issue by sbleon** [sonnym/js-asset_paths#6]
The error comes from https://github.com/sonnym/js-asset_paths/blob/master/lib/js_asset_paths/generator.rb#L14, so `environment.assets` must be `nil` in that context. Precompiling assets locally works, as does deploying to a regular server, so I suspect that the problem has something to do with Heroku's env at the time of asset precompilation.

I might look into this next week. For now, my Heroku-hosted app is stuck on v0.2.0.

**Comment by sonnym** [comment]
That seems to be the same error you noted in the README: https://github.com/sonnym/js-asset_paths/commit/93db37c5e35ab88906f0f18bbad27f0b5b1d7e90#diff-04c6e90faac2675aa89e2176d2eec7d8

I do not see that error when I change (or remove entirely) the configuration variables in https://github.com/sonnym/js-asset_paths/blob/master/test/test_helper.rb so it is pretty weird to me.

If you can provide some additional information, such as Rails version and the application configuration as Heroku sees it, I might be able to write a test.

**Comment by sbleon** [comment]
Doh! Thanks for pointing out that note in the README. Following the advice
of Past Me solved my current problem.
